### ISSUE TITLE
?(help) is no help at all

### ISSUE THREAD

**Issue by Raptor3um** [Raptor3um/Raptoreum#393]
**Chain:** Testnet
**Branch:** Develop
**Build:** v2.0.03.99

All windows which have a ? for "help" have a bug where clicking on the ? has an unexpected result (see video).

**Note:** This appears to be a Windows OS specific issue.

https://github.com/user-attachments/assets/9f6fb899-2300-47b8-ace0-975a3f67cace

There is a bounty of 25k RTM on this issue.

**Comment by drmancini** [comment]
fixed with proposed PR #402

**Comment by HumbleDeer** [comment]
This issue is currently still present in the wallet, but the "red crossed circle" pointer can be exited by clicking any clickable user interface element (buttons etc)

**Comment by Bigpiggy01** [comment]
Can confirm this is still present on Windows. So still open!

Clicking on it now makes it look like a forbidden/invisible windows popsup. Cursor turns into a red forbidden sign.
